{
 "title": "城市",
 "time": { "from": "2017-12-31T16:00:00.000Z", "to": "2018-02-02T15:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "province",
    "label": "省份",
    "query": "select DISTINCT province from 'temp'"
   },
   {
    "name": "city",
    "label": "城市",
    "query": "select DISTINCT city from 'temp' where province = '$province'"
   },
   {
    "name": "province2",
    "label": "空气质量省份",
    "query": "select DISTINCT province from 'aqi' "
   },
   {
    "name": "city2",
    "label": "空气质量城市",
    "query": "select DISTINCT city from 'aqi' where province = '$province2'"
   }
  ]
 },
 "panels": [
  {
   "title": "空气质量",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aqi_2018{province=\"$province2\" ,city=\"$city2\"}",
     "legendFormat": "aqi"
    }
   ]
  },
  {
   "title": "全年空气质量各等级占比",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(value) AS '好' from 'aqi_2018' WHERE  value < 51 AND province=\"$province2\" AND city=\"$city2\""
    },
    {
     "rawSql": "SELECT COUNT(value) AS '中等' from 'aqi_2018' WHERE value < 101 AND value > 50 AND province=\"$province2\" AND city=\"$city2\""
    },
    {
     "rawSql": "SELECT COUNT(value) AS '不适于敏感人群' from 'aqi_2018' WHERE value < 151 AND value > 100 AND province=\"$province2\" AND city=\"$city2\""
    },
    {
     "rawSql": "SELECT COUNT(value) AS '不健康' from 'aqi_2018'  WHERE value < 201 AND value > 150 AND province=\"$province2\" AND city=\"$city2\""
    },
    {
     "rawSql": "SELECT COUNT(value) AS '非常不健康' from 'aqi_2018'  WHERE value < 301 AND value > 200 AND province=\"$province2\" AND city=\"$city2\""
    },
    {
     "rawSql": "SELECT COUNT(value) AS '危险' from 'aqi_2018'  WHERE value > 300 AND province=\"$province2\" AND city=\"$city2\""
    }
   ]
  },
  {
   "title": "温度",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temp{province=\"$province\", city=\"$city\"}",
     "legendFormat": "temp"
    }
   ]
  },
  {
   "title": "降水量",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "prec{province=\"$province\", city=\"$city\"}*24",
     "legendFormat": "prec"
    }
   ]
  },
  {
   "title": "风速(m/s)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "wind{province=\"$province\", city=\"$city\"}",
     "legendFormat": "wind"
    }
   ]
  },
  {
   "title": "城市月份平均温度",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(value) as '1月平均温度' FROM 'temp' WHERE province= \"$province\" AND city = \"$city\" AND t > 1514736000000 AND t < 1517414399000"
    },
    {
     "rawSql": "SELECT AVG(value) as '2月平均温度' FROM 'temp' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1517414400000 AND t < 1519833599000"
    },
    {
     "rawSql": "SELECT AVG(value) as '3月平均温度' FROM 'temp' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1519833600000 AND t < 1522511999000"
    },
    {
     "rawSql": "SELECT AVG(value) as '4月平均温度' FROM 'temp' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1522512000000 AND t < 1525103999000"
    },
    {
     "rawSql": "SELECT AVG(value) as '5月平均温度' FROM 'temp' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1525104000000 AND t < 1527782399000"
    },
    {
     "rawSql": "SELECT AVG(value) as '6月平均温度' FROM 'temp' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1527782400000 AND t < 1530374399000"
    },
    {
     "rawSql": "SELECT AVG(value) as '7月平均温度' FROM 'temp' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1530374400000 AND t < 1533052799000"
    },
    {
     "rawSql": "SELECT AVG(value) as '8月平均温度' FROM 'temp' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1533052800000 AND t < 1535731199000"
    },
    {
     "rawSql": "SELECT AVG(value) as '9月平均温度' FROM 'temp' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1535731200000 AND t < 1538323199000"
    },
    {
     "rawSql": "SELECT AVG(value) as '10月平均温度' FROM 'temp' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1538323200000 AND t < 1541001599000"
    },
    {
     "rawSql": "SELECT AVG(value) as '11月平均温度' FROM 'temp' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1541001600000 AND t < 1543593599000"
    },
    {
     "rawSql": "SELECT AVG(value) as '12月平均温度' FROM 'temp' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1543593600000 AND t < 1546271999000"
    }
   ]
  },
  {
   "title": "城市月份降水天数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(value) as '1月降雨天数' FROM 'prec' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1514736000000 AND t < 1517414399000 AND value > 0"
    },
    {
     "rawSql": "SELECT COUNT(value) as '2月降雨天数' FROM 'prec' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1517414400000 AND t < 1519833599000 AND value > 0"
    },
    {
     "rawSql": "SELECT COUNT(value) as '3月降雨天数' FROM 'prec' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1519833600000 AND t < 1522511999000 AND value > 0"
    },
    {
     "rawSql": "SELECT COUNT(value) as '4月降雨天数' FROM 'prec' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1522512000000 AND t < 1525103999000 AND value > 0"
    },
    {
     "rawSql": "SELECT COUNT(value) as '5月降雨天数' FROM 'prec' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1525104000000 AND t < 1527782399000 AND value > 0"
    },
    {
     "rawSql": "SELECT COUNT(value) as '6月降雨天数' FROM 'prec' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1527782400000 AND t < 1530374399000 AND value > 0"
    },
    {
     "rawSql": "SELECT COUNT(value) as '7月降雨天数' FROM 'prec' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1530374400000 AND t < 1533052799000 AND value > 0"
    },
    {
     "rawSql": "SELECT COUNT(value) as '8月降雨天数' FROM 'prec' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1533052800000 AND t < 1535731199000 AND value > 0"
    },
    {
     "rawSql": "SELECT COUNT(value) as '9月降雨天数' FROM 'prec' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1535731200000 AND t < 1538323199000 AND value > 0"
    },
    {
     "rawSql": "SELECT COUNT(value) as '10月降雨天数' FROM 'prec' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1538323200000 AND t < 1541001599000 AND value > 0"
    },
    {
     "rawSql": "SELECT COUNT(value) as '11月降雨天数' FROM 'prec' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1541001600000 AND t < 1543593599000 AND value > 0"
    },
    {
     "rawSql": "SELECT COUNT(value) as '12月降雨天数' FROM 'prec' WHERE province= \"$province\" AND city = \"$city\"  AND t > 1543593600000 AND t < 1546271999000 AND value > 0"
    }
   ]
  },
  {
   "title": "城市宜出行月份排行(适宜温度)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) AS '1月'\nFROM\n  'temp'\nWHERE\n  t > 1514736000000\n  AND t < 1517414399000\n  AND value > 14\n  AND value < 26\n  AND province = \"$province\"\n  AND city = \"$city\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '2月'\nFROM\n  'temp'\nWHERE\n  t > 1517414400000\n  AND t < 1519833599000\n  AND value > 14\n  AND value < 26\n  AND province = \"$province\"\n  AND city = \"$city\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '3月'\nFROM\n  'temp'\nWHERE\n  province = \"$province\"\n  AND city = \"$city\"\n  AND t > 1519833600000\n  AND t < 1522511999000\n  AND value > 14\n  AND value < 26"
    },
    {
     "rawSql": "SELECT\n  COUNT(value) as '4月'\nFROM\n  'temp'\nWHERE\n  province = \"$province\"\n  AND city = \"$city\"\n  AND t > 1522512000000\n  AND t < 1525103999000\n  AND value > 14\n  AND value < 26"
    },
    {
     "rawSql": "SELECT COUNT(value) as '5月' FROM 'temp' WHERE province = \"$province\"\n  AND city = \"$city\" AND t > 1525104000000 AND t < 1527782399000 AND value > 14 AND value < 26"
    },
    {
     "rawSql": "SELECT COUNT(value) as '6月' FROM 'temp' WHERE province = \"$province\"\n  AND city = \"$city\" AND t > 1527782400000 AND t < 1530374399000 AND value > 14 AND value < 26"
    },
    {
     "rawSql": "SELECT\n  COUNT(value) as '7月'\nFROM\n  'temp'\nWHERE\n  province = \"$province\"\n  AND city = \"$city\"\n  AND t > 1530374400000\n  AND t < 1533052799000\n  AND value > 14\n  AND value < 26"
    },
    {
     "rawSql": "SELECT COUNT(value) as '8月' FROM 'temp' WHERE province = \"$province\"\n  AND city = \"$city\" AND t > 1533052800000 AND t < 1535731199000 AND value > 14 AND value < 26"
    },
    {
     "rawSql": "SELECT COUNT(value) as '9月' FROM 'temp' WHERE province = \"$province\"\n  AND city = \"$city\" AND t > 1535731200000 AND t < 1538323199000 AND value > 14 AND value < 26"
    },
    {
     "rawSql": "SELECT COUNT(value) as '10月' FROM 'temp' WHERE province = \"$province\"\n  AND city = \"$city\" AND t > 1538323200000 AND t < 1541001599000 AND value > 14 AND value < 26"
    },
    {
     "rawSql": "SELECT\n  COUNT(value) as '11月'\nFROM\n  'temp'\nWHERE\n  t > 1541001600000\n  AND t < 1543593599000\n  AND value > 14\n  AND value < 26\n  AND province = \"$province\"\n  AND city = \"$city\""
    },
    {
     "rawSql": "SELECT COUNT(value) as '12月' FROM 'temp' WHERE province = \"$province\"\n  AND city = \"$city\" AND t > 1543593600000 AND t < 1546271999000 AND value > 14 AND value < 26"
    }
   ]
  },
  {
   "title": "城市宜出行月份排行(空气质量)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) AS '1月'\nFROM\n  'aqi'\nWHERE\n  t > 1609430400000\n  AND t < 1612108799000\n  AND value < 51\n  AND province = \"$province2\"\n  AND city = \"$city2\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '2月'\nFROM\n  'aqi'\nWHERE\n  t > 1612108800000\n  AND t < 1614527999000\n  AND value < 51\n  AND province = \"$province2\"\n  AND city = \"$city2\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '3月'\nFROM\n  'aqi'\nWHERE\n  t > 1614528000000\n  AND t < 1617206399000\n  AND value < 51\n  AND province = \"$province2\"\n  AND city = \"$city2\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '4月'\nFROM\n  'aqi'\nWHERE\n  t > 1617206400000\n  AND t < 1619798399000\n  AND value < 51\n  AND province = \"$province2\"\n  AND city = \"$city2\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '5月'\nFROM\n  'aqi'\nWHERE\n  t > 1619798400000\n  AND t < 1622476799000\n  AND value < 51\n  AND province = \"$province2\"\n  AND city = \"$city2\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '6月'\nFROM\n  'aqi'\nWHERE\n  t > 1622476800000\n  AND t < 1625068799000\n  AND value < 51\n  AND province = \"$province2\"\n  AND city = \"$city2\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '7月'\nFROM\n  'aqi'\nWHERE\n  t > 1625068800000\n  AND t < 1627747199000\n  AND value < 51\n  AND province = \"$province2\"\n  AND city = \"$city2\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '8月'\nFROM\n  'aqi'\nWHERE\n  t > 1627747200000\n  AND t < 1630425599000\n  AND value < 51\n  AND province = \"$province2\"\n  AND city = \"$city2\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '9月'\nFROM\n  'aqi'\nWHERE\n  t > 1630425600000\n  AND t < 1633017599000\n  AND value < 51\n  AND province = \"$province2\"\n  AND city = \"$city2\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '10月'\nFROM\n  'aqi'\nWHERE\n  t > 1633017600000\n  AND t < 1635695999000\n  AND value < 51\n  AND province = \"$province2\"\n  AND city = \"$city2\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '11月'\nFROM\n  'aqi'\nWHERE\n  t > 1635696000000\n  AND t < 1638287999000\n  AND value < 51\n  AND province = \"$province2\"\n  AND city = \"$city2\""
    },
    {
     "rawSql": "SELECT\n  COUNT(value) AS '10月'\nFROM\n  'aqi'\nWHERE\n  t > 1638288000000\n  AND t < 1640966399000\n  AND value < 51\n  AND province = \"$province2\"\n  AND city = \"$city2\""
    }
   ]
  },
  {
   "title": "短波辐射(w/m2)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "srad{province=\"$province\", city=\"$city\"}",
     "legendFormat": "srad"
    }
   ]
  },
  {
   "title": "长波辐射(w/m2)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "lrad{province=\"$province\", city=\"$city\"}",
     "legendFormat": "lrad"
    }
   ]
  },
  {
   "title": "比湿(g/kg)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "shum{province=\"$province\", city=\"$city\"}*1000",
     "legendFormat": "shum"
    }
   ]
  },
  {
   "title": "宜居城市排行(适宜温度天数)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT province, city, COUNT(value) as '适宜温度' FROM 'temp' WHERE value > 14 AND value <26 AND t > 1514736000000 AND t < 1546271999000 GROUP BY province, city ORDER BY 适宜温度 DESC LIMIT 20"
    }
   ]
  },
  {
   "title": "宜居城市排行(空气质量好天数)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(value) AS '好', province, city from 'aqi' WHERE  value < 51 GROUP BY province, city ORDER BY 好 DESC LIMIT 20"
    }
   ]
  },
  {
   "title": "1月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '1月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1514736000000\n  AND t < 1517414399000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  1月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  },
  {
   "title": "2月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '2月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1517414400000\n  AND t < 1519833599000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  2月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  },
  {
   "title": "3月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '2月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1519833600000\n  AND t < 1522511999000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  2月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  },
  {
   "title": "4月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '4月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1522512000000\n  AND t < 1525103999000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  4月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  },
  {
   "title": "5月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 124 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '5月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1525104000000\n  AND t < 1527782399000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  5月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  },
  {
   "title": "6月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 137 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '6月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1527782400000\n  AND t < 1530374399000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  6月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  },
  {
   "title": "7月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 150 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '7月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1530374400000\n  AND t < 1533052799000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  7月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  },
  {
   "title": "8月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 163 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '7月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1533052800000\n  AND t < 1535731199000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  7月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  },
  {
   "title": "9月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 176 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '7月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1535731200000\n  AND t < 1538323199000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  7月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  },
  {
   "title": "10月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 189 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '7月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1538323200000\n  AND t < 1541001599000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  7月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  },
  {
   "title": "11月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 202 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '7月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1541001600000\n  AND t < 1543593599000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  7月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  },
  {
   "title": "11月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 215 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '7月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1541001600000\n  AND t < 1543593599000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  7月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  },
  {
   "title": "12月份宜出行城市排行",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 228 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(value) as '7月适宜温度天数',\n  province,\n  city\nFROM\n  'temp'\nWHERE\n  t > 1543593600000\n  AND t < 1546271999000\n  AND value > 14\n  AND value < 26\nGROUP BY\n  province,\n  city\nORDER BY\n  7月适宜温度天数 DESC\nLIMIT\n  20"
    }
   ]
  }
 ]
}